### ISSUE TITLE
Political affiliation question mislabeled as 'news'

### ISSUE THREAD

**Issue by postylem** [vboyce/mmepr24#2]
Should be "political_affiliation" or something here, rather than "news"
https://github.com/vboyce/mmepr24/blob/195bc4cae35f677733da72123c1d06918f4b56ca/experiment/src/instructions.js#L166

The demographic information about political affiliation was given the name “news”, which is a duplicate for the question that was actually about news. Unfortunately this seems to have resulted in responses to the political affiliation question overwriting whatever responses were given for the news habits.

**Comment by vboyce** [comment]
resolved by most recent commit
